version: "3.7"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  coinapp:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
volumes:
  db:
    driver: local
